/* DEFINE_ERROR(error_no, id, str) */
DEFINE_ERROR( 0, VSK_NO_ERROR,                  "No error")
DEFINE_ERROR( 1, VSK_ERR_NEXT_WITHOUT_FOR,      "NEXT without FOR")
DEFINE_ERROR( 2, VSK_ERR_SYNTAX,                "Syntax error")
DEFINE_ERROR( 3, VSK_ERR_RETURN_WITHOUT_GOSUB,  "RETURN without GOSUB")
DEFINE_ERROR( 4, VSK_ERR_OUT_OF_DATA,           "Out of DATA")
DEFINE_ERROR( 5, VSK_ERR_BAD_CALL,              "Illegal function call")
DEFINE_ERROR( 6, VSK_ERR_OVERFLOW,              "Overflow")
DEFINE_ERROR( 7, VSK_ERR_NO_MEMORY,             "Out of memory")
DEFINE_ERROR( 8, VSK_ERR_BAD_LINE_NO,           "Undefined line number")
DEFINE_ERROR( 9, VSK_ERR_BAD_INDEX,             "Subscript out of range")
DEFINE_ERROR(10, VSK_ERR_DUPLICATE_DEFINE,      "Duplicate Definition")
DEFINE_ERROR(11, VSK_ERR_DIV_BY_ZERO,           "Division by Zero")
DEFINE_ERROR(12, VSK_ERR_BAD_DIRECT,            "Illegal direct")
DEFINE_ERROR(13, VSK_ERR_BAD_TYPE,              "Type mismatch")
DEFINE_ERROR(14, VSK_ERR_NO_STRING_SPACE,       "Out of string space")
DEFINE_ERROR(15, VSK_ERR_STRING_TOO_LONG,       "String too long")
DEFINE_ERROR(16, VSK_ERR_STRING_TOO_COMPLEX,    "String formula too complex")
DEFINE_ERROR(17, VSK_ERR_CANT_CONTINUE,         "Can't continue")
DEFINE_ERROR(18, VSK_ERR_UNDEFINED_FUNCTION,    "Undefined user function")
DEFINE_ERROR(19, VSK_ERR_NO_RESUME,             "No RESUME")
DEFINE_ERROR(20, VSK_ERR_RESUME_WITHOUT_ERROR,  "RESUME without error")
DEFINE_ERROR(22, VSK_ERR_MISSING_OPERAND,       "Missing operand")
DEFINE_ERROR(23, VSK_ERR_LINE_BUFFER_OVER,      "Line buffer overflow")
DEFINE_ERROR(26, VSK_ERR_FOR_WITHOUT_NEXT,      "FOR without NEXT")
DEFINE_ERROR(27, VSK_ERR_BAD_TAPE_READ,         "Tape read error")
DEFINE_ERROR(29, VSK_ERR_WHILE_WITHOUT_WEND,    "WHILE without WEND")
DEFINE_ERROR(30, VSK_ERR_WEND_WITHOUT_WHILE,    "WEND without WHILE")
DEFINE_ERROR(31, VSK_ERR_DUPLICATE_LABEL,       "Duplicate label")
DEFINE_ERROR(32, VSK_ERR_UNDEFINED_LABEL,       "Undefined label")
DEFINE_ERROR(33, VSK_ERR_NO_FEATURE,            "Feature not available")
DEFINE_ERROR(50, VSK_ERR_FIELD_OVERFLOW,        "FIELD overflow")
DEFINE_ERROR(52, VSK_ERR_BAD_FILE_NO,           "Bad file number")
DEFINE_ERROR(53, VSK_ERR_FILE_NOT_FOUND,        "File not found")
DEFINE_ERROR(54, VSK_ERR_FILE_ALREADY_OPEN,     "File already open")
DEFINE_ERROR(55, VSK_ERR_INPUT_PAST_END,        "Input past end")
DEFINE_ERROR(56, VSK_ERR_BAD_FILE_NAME,         "Bad file name")
DEFINE_ERROR(57, VSK_ERR_DIRECT_IN_FILE,        "Direct statement in file")
DEFINE_ERROR(59, VSK_ERR_SEQUENTIAL_IO_ONLY,    "Sequential I/O only")
DEFINE_ERROR(60, VSK_ERR_FILE_NOT_OPEN,         "File not open")
DEFINE_ERROR(61, VSK_ERR_WRITE_PROTECTED,       "File write protected")
DEFINE_ERROR(62, VSK_ERR_DISK_OFFLINE,          "Disk offline")
DEFINE_ERROR(64, VSK_ERR_DISK_IO_ERROR,         "Disk I/O error")
DEFINE_ERROR(65, VSK_ERR_FILE_ALREADY_EXIST,    "File already exist")
DEFINE_ERROR(68, VSK_ERR_DISK_FULL,             "Disk full")
DEFINE_ERROR(69, VSK_ERR_BAD_ALLOC_TABLE,       "Bad allocation table")
DEFINE_ERROR(70, VSK_ERR_BAD_DRIVE_NO,          "Bad drive number")
DEFINE_ERROR(71, VSK_ERR_BAD_TRACK_SECTOR,      "Bad track/sector")
DEFINE_ERROR(73, VSK_ERR_RENAME_ACROSS_DISK,    "Rename across disk")
DEFINE_ERROR(74, VSK_ERR_BAD_OPERATION,         "Illegal operation")
/* DEFINE_ERROR(??, VSK_ERR_UNPRINTABLE,           "Unprintable error") */
