//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.8.5.
// VeySicK_res.rc

#define IDD_SETTINGS                        100

#define IDI_MAINICON                        100

#define IDR_MAINMENU                        100
#define IDR_POPUPMENU                       101

#define IDS_OPEN_IMAGE                      100
#define IDS_FOLDER                          101
#define IDS_SAVESHOTFILTER                  102
#define IDS_SCREENSHOT                      103
#define IDS_SAVESHOTTITLE                   104
#define IDS_SETTINGS                        105

#define ID_EXIT                             100
#define ID_RESET                            101
#define ID_LOAD                             102
#define ID_LOAD_RUN                         103
#define ID_SAVE                             104
#define ID_DRIVE1_IMAGE                     105
#define ID_DRIVE2_IMAGE                     106
#define ID_DRIVE3_IMAGE                     107
#define ID_DRIVE4_IMAGE                     108
#define ID_DRIVE1_EJECT                     109
#define ID_DRIVE2_EJECT                     110
#define ID_DRIVE3_EJECT                     111
#define ID_DRIVE4_EJECT                     112
#define ID_DRIVE1_FOLDER                    113
#define ID_DRIVE2_FOLDER                    114
#define ID_DRIVE3_FOLDER                    115
#define ID_DRIVE4_FOLDER                    116
#define ID_ZOOM_X1                          117
#define ID_ZOOM_X2                          118
#define ID_ZOOM_X3                          119
#define ID_SAVE_SCREENSHOT                  120
#define ID_ABOUT                            121
#define ID_OPEN_README                      122
#define ID_MACHINE_8801                     123
#define ID_MACHINE_9801                     124
#define ID_SAVE_AS                          126
#define ID_COPY_SCREENSHOT                  127
#define ID_MAXIMIZE                         128
#define ID_NEW_DISK                         129
#define ID_SETTINGS                         131
#define ID_PASTE_TEXT                       132
#define ID_COPY_TEXT                        133
#define ID_GRPH_MODE                        134
#define ID_SJIS_MODE                        135
#define ID_JIS_MODE                         136
#define ID_UNLIMITED_MODE                   137

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    102
        #define _APS_NEXT_COMMAND_VALUE     138
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
